#!/bin/bash

#set -x

MYSQL_USERNAME="root"
MYSQL_DATABASE="steelfig"

# Create db if it doesn't already exist
mysql -u$MYSQL_USERNAME -e "CREATE SCHEMA IF NOT EXISTS $MYSQL_DATABASE DEFAULT CHARACTER SET utf8;"

# Select version
VERSION=$(mysql -D$MYSQL_DATABASE -u$MYSQL_USERNAME -e "SELECT version FROM versions ORDER
        BY id DESC LIMIT 1;" -sN 2> /dev/null )

# Need to decide if we are starting at the begining or not
if [ "$VERSION" == "" ]; then
    CAN_APPLY=true
else
    CAN_APPLY=false
fi


# Apply patch
for dir in `\ls -d */ | sort`
do
    if [ $CAN_APPLY == true ]; then
        mysql -D$MYSQL_DATABASE -u$MYSQL_USERNAME < ${dir}manifest.sql
        if [ $? -ne 0 ]; then
            >&2 echo "Error applying patch: ${dir}"
            break
        else
            VERSION=${dir}
        fi
    fi

    if [ "${dir}" == "$VERSION" ]; then
        CAN_APPLY=true
    fi
done

# Set updated version
mysql -D$MYSQL_DATABASE -u$MYSQL_USERNAME -e "INSERT INTO versions SET version = '$VERSION'"

echo "$MYSQL_DATABASE at version $VERSION"
